#!/usr/bin/env node
// Generated by LiveScript 1.3.0
(function(){
  "use strict";
  var fs, path, _, __, ___, debug, lock, npmDir, getCommandOptions, initLiquid, genProfile, checkExistingProfile, copy, restartApparmor, getNextAvailable, putBack, main;
  fs = require('fs');
  path = require('path');
  _ = require('shelljs');
  __ = require('bluebird');
  ___ = require('lodash');
  debug = require('debug')('apparmorize');
  lock = require('lockfile');
  fs = __.promisifyAll(fs);
  npmDir = path.dirname(__filename);
  getCommandOptions = function(){
    var docopt, doc, getOption, o, spoolDir, templateName, go, numberOfInstances, install, run, program;
    docopt = require('docopt').docopt;
    doc = _.cat(__dirname + "/docs/usage.md");
    getOption = function(a, b, def, o){
      if (!o[a] && !o[b]) {
        return def;
      } else {
        return o[b];
      }
    };
    o = docopt(doc);
    spoolDir = getOption('-s', '--spool', process.cwd() + "/spool", o);
    templateName = getOption('-p', '--profile', 'standard', o);
    go = getOption('-g', '--go', false, o);
    numberOfInstances = getOption('-n', '--number', 1, o);
    numberOfInstances = parseInt(numberOfInstances);
    install = o['install'] != null && o['install'];
    run = o['run'] != null && o['run'];
    program = o['PROGRAM'];
    return {
      install: install,
      run: run,
      go: go,
      spoolDir: path.resolve(spoolDir),
      templateName: templateName,
      program: program,
      numberOfInstances: numberOfInstances
    };
  };
  initLiquid = function(){
    var engine;
    engine = require('liquid-node').Engine;
    return new engine();
  };
  genProfile = function(liquid, commandName, spoolDir, templateNameA, go){
    var templateData, fileName, absoluteFilename, profileName, object;
    templateData = fs.readFileSync(templateNameA, 'utf-8');
    spoolDir = path.resolve(spoolDir);
    fileName = spoolDir + "/" + commandName;
    absoluteFilename = path.resolve(fileName);
    profileName = absoluteFilename.replace('/', '');
    profileName = profileName.replace(/\//g, '.');
    object = {
      profile: {
        date: require('moment')().format('MMMM DDD, YYYY - HH:MM'),
        programName: absoluteFilename,
        profileName: profileName
      }
    };
    return liquid.parseAndRender(templateData, object).then(function(it){
      if (!go) {
        console.log("Will write profile to " + spoolDir + "/" + profileName);
        return spoolDir + "/" + profileName;
      } else {
        debug("Writing profile to " + spoolDir + "/" + profileName);
        return fs.writeFileAsync(spoolDir + "/" + profileName, it, 'utf-8').then(function(){
          return spoolDir + "/" + profileName;
        });
      }
    });
  };
  checkExistingProfile = function(templateName){
    var templateNameA;
    templateNameA = npmDir + "/profiles/" + templateName + "/profile.txt";
    if (!_.test('-e', templateNameA + "")) {
      console.log("Sorry, profile '" + templateNameA + "' does not exist");
      process.exit(1);
    }
    return {
      templateNameA: templateNameA
    };
  };
  copy = function(name, fromDir, go){
    var completeName, destinationName;
    completeName = name + "";
    destinationName = "/etc/apparmor.d";
    if (!go) {
      return console.log("Will copy " + completeName + " to " + destinationName);
    } else {
      debug("Copying " + completeName + " to " + destinationName);
      return _.cp(completeName, destinationName);
    }
  };
  restartApparmor = function(go){
    if (!go) {
      return console.log("Will restart apparmor");
    } else {
      debug("Will restart apparmor");
      return __.promisify(_.exec)("service apparmor reload");
    }
  };
  getNextAvailable = function(config){
    var data, av;
    data = JSON.parse(_.cat(config));
    av = ___.filter(data.resources, function(it){
      return it.available;
    });
    if (av.length === 0) {
      debug("No resource available");
      return 0;
    } else {
      av[0].available = false;
      debug("Got " + av[0].number);
      debug(data);
      return av[0].number;
    }
  };
  putBack = function(config, n){
    var data, av;
    data = JSON.parse(_.cat(config));
    av = ___.filter(data.resources, function(it){
      return it.number === n;
    });
    av[0].available = true;
    debug("Restored resource");
    return debug(data);
  };
  main = function(){
    var opts, install, run, templateName, templateNameA, liquid, numberOfInstances, spoolDir, program, config, lockFile, n, error;
    opts = getCommandOptions();
    debug(opts);
    install = opts.install, run = opts.run;
    if (install) {
      templateName = opts.templateName;
      templateNameA = checkExistingProfile(templateName).templateNameA;
      liquid = initLiquid();
      numberOfInstances = opts.numberOfInstances, spoolDir = opts.spoolDir, templateName = opts.templateName;
      _.mkdir('-p', spoolDir);
      return __.all((function(){
        var i$, to$, results$ = [];
        for (i$ = 1, to$ = numberOfInstances; i$ <= to$; ++i$) {
          results$.push(i$);
        }
        return results$;
      }()).map(function(i){
        return genProfile(liquid, "cmd-" + i, spoolDir, templateNameA, opts.go).then(function(it){
          return copy(it, spoolDir, opts.go);
        });
      })).then(function(){
        var dta, res$, i$, ref$, len$, i;
        dta = {};
        res$ = [];
        for (i$ = 0, len$ = (ref$ = (fn$())).length; i$ < len$; ++i$) {
          i = ref$[i$];
          res$.push({
            number: i,
            available: true
          });
        }
        dta.resources = res$;
        return JSON.stringify(dta, 0, 4).to(spoolDir + "/config.json");
        function fn$(){
          var i$, to$, results$ = [];
          for (i$ = 1, to$ = numberOfInstances; i$ <= to$; ++i$) {
            results$.push(i$);
          }
          return results$;
        }
      }).then(function(){
        return restartApparmor(opts.go);
      }).then(function(){
        return console.log("done.");
      }).error(function(it){
        return console.error("Sorry, cannot install: " + it);
      });
    } else {
      spoolDir = opts.spoolDir, program = opts.program;
      config = spoolDir + "/config.json";
      lockFile = spoolDir + "/lock";
      lock.lockAsync = __.promisify(lock.lock);
      lock.unlockAsync = __.promisify(lock.unlock);
      try {
        return lock.lockAsync(lockFile).then(function(){
          return n = getNextAvailable(config);
        }).then(function(){
          return lock.unlockAsync(lockFile);
        }).then(function(){
          if (n === 0) {
            return console.error("all slots are taken.");
          } else {
            _.cp('-f', path.resolve(program), spoolDir + "/cmd-" + n);
            return __.promisify(_.exec)(spoolDir + "/cmd-" + n)['finally'](function(){
              return lock.lockAsync(lockFile, {
                retries: 3,
                retryWait: 100
              }).then(function(){
                return putBack(config, n);
              }).then(function(){
                return lock.unlockAsync(lockFile);
              });
            });
          }
        });
      } catch (e$) {
        error = e$;
        return console.error("Sorry, " + error);
      }
    }
  };
  main();
}).call(this);
